[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0016"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"


[[keyboard.bindings]]
chars = "\u0003"
key = "С"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0016"
key = "М"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "М"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "М"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "С"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "С"
mods = "Control|Shift"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15

[selection]
save_to_clipboard = true