config_version = 14

[audio]
enable_sounds = true

[bar]
order = [ "polibar" ]

    [bar.polibar]
    background_opacity = 0.69999998435378075
    center = []
    end = [
        "tray",
        "bluetooth",
        "volume",
        "keyboard_layout",
        "widget",
        "network",
        "battery",
        "notifications",
        "date",
        "bar"
    ]
    font_family = "JetBrainsMono Nerd Font"
    margin_ends = 0
    radius = 0
    radius_bottom_left = 10
    radius_bottom_right = 10
    start = [ "launcher", "control-center", "active_window" ]
    thickness = 32
    widget_spacing = 10

[calendar]
enabled = true

    [calendar.account.personal_google]
    type = "google"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
auto_hide = true
enabled = true
reserve_space = false
show_dots = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@eDP-1",
    "lockscreen-login-box@DP-2",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004",
    "lockscreen-widget-0000000000000005",
    "lockscreen-widget-0000000000000006"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = false

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 942.0
    output = "DP-2"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = true
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 985.0
    cy = 1049.0
    output = "eDP-1"
    placement_height = 1600.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 208.0
    box_width = 736.0
    cx = 1280.0
    cy = 148.0
    output = "DP-2"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "clock"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 112.0
    box_width = 496.0
    cx = 1280.0
    cy = 324.0
    output = "DP-2"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "weather"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 1280.0
    cy = 540.0
    output = "DP-2"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 224.0
    box_width = 608.0
    cx = 984.5
    cy = 151.5
    output = "eDP-1"
    placement_height = 1600.0
    placement_width = 2560.0
    rotation = 0.0
    type = "clock"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 96.0
    box_width = 416.0
    cx = 984.5
    cy = 327.5
    output = "eDP-1"
    placement_height = 1600.0
    placement_width = 2560.0
    rotation = 0.0
    type = "weather"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000006]
    box_height = 0.0
    box_width = 0.0
    cx = 984.5
    cy = 615.5
    output = "eDP-1"
    placement_height = 1600.0
    placement_width = 2560.0
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000006.settings]
        background = false

[notification]
layer = "overlay"

[plugin_settings."kenn/keybind-cheatsheet"]
compositor = "niri"

[plugin_settings."yuuto/arch-updater"]
aur_helper = "off"
auto_check_hours = 1
terminal = "alacritty --class hyprdots-float"
update_cmd = "bash ~/.config/niri/sh/pacman/update.sh && bash ~/.config/niri/sh/pacman/unused.sh"

[plugins]
auto_update = "all"
enabled = [ "kenn/keybind-cheatsheet", "yuuto/arch-updater", "raycursive/niri-displays" ]

[shell]
avatar_path = "/home/snippik/.face.icon"
font_family = "JetBrainsMono Nerd Font"
password_style = "random"
polkit_agent = true

    [shell.animation]
    speed = 1.3000000193715096

    [shell.launcher.providers.emoji]
    global = false

    [shell.panel]
    launcher_placement = "attached"
    launcher_position = "auto"
    open_near_click_control_center = true
    open_near_click_launcher = true

[theme]
builtin = "Noctalia"
community_palette = "Oxocarbon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "alacritty", "gtk3", "gtk4", "qt" ]

[wallpaper.default]
path = "/home/snippik/Pictures/Wallpapers/Static/Nature/[6K] Winter.jpg"

[wallpaper.last]
path = "/home/snippik/Pictures/Wallpapers/Static/Nature/[6K] Winter.jpg"

[wallpaper.monitors.DP-2]
path = "/home/snippik/Pictures/Wallpapers/Static/City/[4K] Fog sity.jpg"

[wallpaper.monitors.HDMI-A-1]
path = "/home/snippik/Pictures/Wallpapers/Static/Nature/[6K] Winter.jpg"

[wallpaper.monitors.eDP-1]
path = "/home/snippik/Pictures/Wallpapers/Static/Nature/[6K] Winter.jpg"

[widget.active_window]
display = "text_only"
title_scroll = "on_hover"

[widget.bar]
show_resolution = false
type = "raycursive/niri-displays:bar"

[widget.battery]
display_mode = "graphic"
hide_when_full = true
show_label = false

[widget.date]
format = "{:%H:%M}"

[widget.keyboard_layout]
hide_when_single_layout = true
show_label = false

[widget.launcher]
font_family = "JetBrainsMono Nerd Font"
glyph = "navigation-filled"

[widget.network]
show_label = false

[widget.tray]
drawer = true

[widget.volume]
show_label = false

[widget.widget]
type = "yuuto/arch-updater:widget"