#!/bin/sh
# -----------------------------------------------------

echo "Settings help"
echo "> Hyprland"
echo "    Open             - hyprland"
echo "    Open dir         - chyprland"
echo "    Open env file    - hyprland-env"
echo "    Open autostart   - hyprland-start"
echo "    Open binds       - hyprland-binds"
echo "    Open keybinds    - hyprland-board"
echo " "
echo "> Waybar"
echo "    Open             - wb"
echo "    Open dir         - cwb"
echo "    Player toggle    - player"
echo " "
echo "> hyprdots"
echo "    Open dir         - chyprdots"
echo "    Update           - dotsync"
echo " "
echo "> System"
echo "    Open wifi        - wifi"
echo "    Open grub        - grub"
echo "    Open mkinitcpio  - mkinitcpio"
echo "    Shutdown sys     - shutdown"
echo " "
read -p "Press enter to close"