#!/bin/sh
# -----------------------------------------------------

echo "Settings help"
echo "> Hyprland"
echo "    Open             - hyprland"
echo "    Open dir         - cd-hyprland"
echo "    Open env file    - hyprland-env"
echo "    Open autostart   - hyprland-start"
echo "    Open binds       - hyprland-binds"
echo "    Open keybinds    - hyprland-board"
echo " "
echo "> Waybar"
echo "    Open             - wb"
echo "    Open dir         - cd-waybar"
echo "    Player toggle    - player"
echo " "
echo "> hyprdots"
echo "    Open dir         - cd-hyprdots"
echo "    Update           - dotsync"
echo " "
echo "> System"
echo "    Open wifi        - wifi"
echo "    Open grub        - grub"
echo "    Open mkinitcpio  - mkinitcpio"
echo " "
echo "    Update system    - update"
echo "    Remove unused    - unused"
echo "    Shutdown sys     - shutdown"