[colors.primary]
background = '#121415'
foreground = '#e2e2e3'

[colors.cursor]
text = '#121415'
cursor = '#e2e2e3'

[colors.vi_mode_cursor]
text = '#121415'
cursor = '#a6ccdd'

[colors.search.matches]
foreground = '#41484b'
background = '#d6bee3'

[colors.search.focused_match]
foreground = '#41484b'
background = '#a6ccdd'

[colors.footer_bar]
foreground = '#41484b'
background = '#e2e2e3'

[colors.hints.start]
foreground = '#41484b'
background = '#bac9d0'

[colors.hints.end]
foreground = '#41484b'
background = '#bac9d0'

[colors.selection]
text = '#c1c7cb'
background = '#41484b'


[colors.normal]
black   = '#41484b'
red     = '#ffb4ab'
green   = '#a6ccdd'
yellow  = '#bac9d0'
blue    = '#d6bee3'
magenta = '#a6ccdd'
cyan    = '#bac9d0'
white   = '#e2e2e3'


[colors.bright]
black   = '#8b9295'
red     = '#ffb4ab'
green   = '#a6ccdd'
yellow  = '#bac9d0'
blue    = '#d6bee3'
magenta = '#a6ccdd'
cyan    = '#bac9d0'
white   = '#e2e2e3'


[colors.dim]
black   = '#41484b'
red     = '#ffb4ab'
green   = '#a6ccdd'
yellow  = '#bac9d0'
blue    = '#d6bee3'
magenta = '#a6ccdd'
cyan    = '#bac9d0'
white   = '#e2e2e3'
